"""Rebuild one deterministic, entirely fictional text-PDF fixture."""

from pathlib import Path
import textwrap

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen.canvas import Canvas


OUTPUT = Path(__file__).resolve().parents[1] / "fixtures" / "synthetic-notice.pdf"
PARAGRAPHS = [
    "SYNTHETIC FIXTURE - no real school, student, contact information or personal records.",
    "Title: After-school reading club - fictional example",
    "Date: 2026-10-08   Time: 15:00   Place: Demo Room A",
    "Action: Bring a notebook. This fictional notice is a software demonstration input, not an actual school instruction.",
    "The demo reading club invites fictional participants to read a short story and discuss its characters. The session begins at the fixed date and time above. The room label is invented for this fixture.",
    "A notebook is the only listed preparation item. No registration, payment, consent form, identity document, telephone number, address or student name is requested. No real consultation or school event is represented.",
    "Participants in this fictional scenario first hear an introduction, then discuss a passage, and finally write a short reflection. This text exists to exercise PDF extraction and overlapping text windows in the actual notice helpers.",
    "The demo's structured summary and four language responses are handwritten JSON fixtures. They were not generated by Gemini and do not measure translation quality. Stored objects and database rows exist only in memory.",
    "A successful replay demonstrates parsing, validation, chunking and orchestration control flow. It does not verify S3, Titan vectors, PostgreSQL transaction behavior, pgvector retrieval or the production Streamlit app.",
]


def build():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    pdf = Canvas(str(OUTPUT), pagesize=A4, invariant=1)
    pdf.setTitle("Synthetic school notice - component demo fixture")
    pdf.setAuthor("School Buddy synthetic demo")
    _, height = A4
    pdf.setFillColor(HexColor("#174A5B"))
    pdf.setFont("Helvetica-Bold", 21)
    pdf.drawString(54, height - 62, "SYNTHETIC SCHOOL NOTICE")
    pdf.setFillColor(HexColor("#475569"))
    pdf.setFont("Helvetica", 10)
    y = height - 94
    for paragraph in PARAGRAPHS:
        for line in textwrap.wrap(paragraph, width=88):
            pdf.drawString(54, y, line)
            y -= 15
        y -= 9
    pdf.setFillColor(HexColor("#64748B"))
    pdf.setFont("Helvetica", 9)
    pdf.drawString(54, 38, "Fixture v1 | Real PDF parser; model and services are mocked | 1 / 1")
    pdf.save()


if __name__ == "__main__":
    build()
